### ISSUE TITLE
Also add `testCompileOnly` for jvm and android targets

### ISSUE THREAD

**Issue by steve-the-edwards** [JakeWharton/cite#100]
As currently, `compileOnly` won't make it available for tests - https://discuss.gradle.org/t/compileonly-dependencies-are-not-available-in-tests/15366

**Comment by JakeWharton** [comment]
Probably also `androidTestCompileOnly` for Android then

**Comment by steve-the-edwards** [comment]
Ya, i'm working on a PR

**Comment by steve-the-edwards** [comment]
No direct API, asking about the configuration on the dependency handler here - https://kotlinlang.slack.com/archives/C7L3JB43G/p1732307930860859

**Comment by JakeWharton** [comment]
You should be able to do something like
```kotlin
kotlin.sourceSets.getByName(TEST_SOURCE_SET_NAME).dependencies {
  compileOnly(target.citeApiDependency())
}
```
for regular tests.

For android tests probably has to be done by the configuration name on the root dependency container.
