### ISSUE TITLE
Generated code implementation detail testing

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/cite#4]
Need to validate output for Java bytecode, JS, WASM, and LLVM IR. Also that the resulting string is a `const` (likely through the use of concatenation and validating that compile-time folding occurred).

**Comment by yamin8000** [comment]
I'm simply curious.  
Are any tests going to be done with GraalVM for this lib?  
Or that's just under LLVM category?

**Comment by JakeWharton** [comment]
The input to GraalVM is still Java bytecode, so as long as we emit string constants at that stage there's nothing additional needed for its support.

**Comment by JakeWharton** [comment]
3b8dbc5c48b355d441372bbe0b599b4ec172cdf7
